# Generated by Django 5.2.17 on 2026-08-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coletas',
            fields=[
                ('id_coleta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_transacao', models.CharField(max_length=64, unique=True)),
                ('total_pontos_gerados', models.IntegerField()),
                ('data_coleta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coletas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ecopontos',
            fields=[
                ('id_ecoponto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('ativo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ecopontos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItensColeta',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pontos_ganhos', models.IntegerField()),
                ('qrcode_lote', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'itens_coleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('cor_nbr', models.CharField(max_length=20)),
                ('codigo_hex', models.CharField(max_length=7)),
                ('pontos_por_kg', models.IntegerField()),
            ],
            options={
                'db_table': 'materiais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfis',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'perfis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recompensas',
            fields=[
                ('id_recompensa', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('custo_pontos', models.IntegerField()),
                ('estoque', models.IntegerField()),
                ('ativo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recompensas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resgates',
            fields=[
                ('id_resgate', models.AutoField(primary_key=True, serialize=False)),
                ('pontos_gastos', models.IntegerField()),
                ('codigo_voucher', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('data_resgate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resgates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('qrcode_token', models.CharField(max_length=64, unique=True)),
                ('saldo_pontos', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwDashboardMetricas',
            fields=[
                ('total_usuarios', models.BigIntegerField(primary_key=True, serialize=False)),
                ('total_kg_reciclados', models.DecimalField(decimal_places=2, max_digits=30)),
                ('total_pontos_distribuidos', models.DecimalField(decimal_places=0, max_digits=32)),
                ('total_resgates_concluidos', models.BigIntegerField()),
            ],
            options={
                'db_table': 'vw_dashboard_metricas',
                'managed': False,
            },
        ),
    ]
